# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='vvv@gmail.com', max_length=200, unique=True)),
                ('check', models.CharField(default='Nothing', max_length=2000)),
            ],
        ),
    ]
